### ISSUE TITLE
path as ReadonlySpan<char> or string instead of ReadonlySpan<byte>

### ISSUE THREAD

**Issue by seertenedos** [tmds/Tmds.Fuse#21]
wouldn't it make more sense for the path to be either a readonly span of char or a string instead of a span of bytes as most file systems would need to convert it to characters or strings for comparisons potentially multiple times.

**Comment by tmds** [comment]
At the lowest level, I prefer these to be bytes because to turn them into chars/strings you need to allocate, and assume an Encoding (e.g. UTF-8).

Probably it should be do-able to build a wrapper that implements `IFuseFileSystem` and calls into a similar interface with `string` arguments.

**Comment by seertenedos** [comment]
Can it be non utf-8 on Linux? Sorry libraries I used in the past just give strings so never knew the encoding. Based it partly off your example.

If it is set to dotnet core instead of netstandard then I though it does not allocate for the encoding/string/readonly char span on top of a read-only byte span.

I have not done a heap of reading on it but I though that was how it was meant to work.

I can look at building and interface and conversion implementation but it just seemed to be very rare people would want paths etc in bytes as I did not know the encoding changes on Linux. Any idea how to detect the correct encoding?

**Comment by tmds** [comment]
> Can it be non utf-8 on Linux?

yes, names are bytes terminated with a `\0`, they can be any encoding.

> If it is set to dotnet core instead of netstandard then I though it does not allocate for the encoding/string/readonly char span on top of a read-only byte span.

It's non-allocating if you explicitly handle that with `stackalloc`, otherwise there is some allocation going on because `string` and `char` are UTF-16.

> Any idea how to detect the correct encoding?

https://unix.stackexchange.com/questions/2089/what-charset-encoding-is-used-for-filenames-and-paths-on-linux

Can you try to implement something like `FuseFileSystemBase`, e.g. `FuseFileSystemEncodingBase` that accepts an `Encoding` in its constructor and which has virtual methods that use `string` instead of `Span<byte>`? If that works, I'd be interested in including it in the library.
